# Generated by Django 3.0.6 on 2022-06-19 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=400)),
                ('iden', models.CharField(blank=True, max_length=400)),
                ('command', models.CharField(blank=True, max_length=100000000)),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=400)),
                ('iden', models.CharField(blank=True, max_length=400)),
                ('message', models.TextField(blank=True, max_length=100000000)),
            ],
        ),
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=400)),
                ('iden', models.CharField(blank=True, max_length=400)),
                ('message', models.TextField(blank=True, max_length=100000000)),
            ],
        ),
    ]
