# Generated by Django 3.0.6 on 2022-08-24 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=400)),
                ('serial_num', models.CharField(blank=True, max_length=400)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('message', models.TextField(blank=True, default='[]', max_length=1048576)),
                ('message_count', models.DecimalField(decimal_places=2, default=0, max_digits=50)),
                ('active', models.CharField(blank=True, default='True', max_length=400)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iden', models.CharField(blank=True, max_length=400)),
                ('Script', models.TextField(blank=True, default='[]', max_length=10485760)),
                ('script_count', models.DecimalField(decimal_places=2, default=0, max_digits=50)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iden', models.CharField(blank=True, max_length=400)),
                ('message', models.TextField(blank=True, default='[]', max_length=1048576)),
                ('message_count', models.DecimalField(decimal_places=2, default=0, max_digits=50)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommandResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iden', models.CharField(blank=True, max_length=400)),
                ('command', models.CharField(blank=True, default='[]', max_length=10485760)),
                ('command_count', models.DecimalField(decimal_places=2, default=0, max_digits=50)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iden', models.CharField(blank=True, max_length=400)),
                ('command', models.CharField(blank=True, default='[]', max_length=10485760)),
                ('command_count', models.DecimalField(decimal_places=2, default=0, max_digits=50)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
