# Generated by Django 3.0.6 on 2022-08-26 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remote', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iden', models.CharField(blank=True, max_length=400)),
                ('alert', models.TextField(blank=True, default='[]', max_length=1048576)),
                ('alert_count', models.DecimalField(decimal_places=2, default=0, max_digits=50)),
            ],
        ),
    ]
