# Generated by Django 3.0.6 on 2022-06-19 20:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('remote', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='script',
            name='message',
        ),
        migrations.AddField(
            model_name='command',
            name='command_count',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50),
        ),
        migrations.AddField(
            model_name='messages',
            name='message_count',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50),
        ),
        migrations.AddField(
            model_name='script',
            name='Script',
            field=models.TextField(blank=True, default='{}', max_length=100000000),
        ),
        migrations.AddField(
            model_name='script',
            name='script_count',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50),
        ),
        migrations.AlterField(
            model_name='command',
            name='command',
            field=models.CharField(blank=True, default='{}', max_length=100000000),
        ),
        migrations.AlterField(
            model_name='command',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='messages',
            name='message',
            field=models.TextField(blank=True, default='{}', max_length=100000000),
        ),
        migrations.AlterField(
            model_name='messages',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='script',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
