# Generated by Django 3.0.6 on 2022-06-19 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remote', '0003_snippet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Snippet',
        ),
    ]
