# Generated by Django 3.0.6 on 2022-06-20 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('remote', '0004_delete_snippet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='command',
            field=models.CharField(blank=True, default='[]', max_length=100000000),
        ),
        migrations.AlterField(
            model_name='messages',
            name='message',
            field=models.TextField(blank=True, default='[]', max_length=100000000),
        ),
        migrations.AlterField(
            model_name='script',
            name='Script',
            field=models.TextField(blank=True, default='[]', max_length=100000000),
        ),
        migrations.CreateModel(
            name='CommandResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iden', models.CharField(blank=True, max_length=400)),
                ('command', models.CharField(blank=True, default='[]', max_length=100000000)),
                ('command_count', models.DecimalField(decimal_places=2, default=0, max_digits=50)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
