# Generated by Django 3.0.6 on 2022-08-27 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remote', '0004_userdata_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='short_cuts',
            field=models.TextField(blank=True, default='[]', max_length=1048576),
        ),
    ]
