# Generated by Django 3.0.6 on 2022-06-21 22:05

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('remote', '0005_auto_20220620_1201'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_num', models.CharField(blank=True, max_length=400)),
                ('last_seen', models.CharField(blank=True, default=datetime.datetime(2022, 6, 21, 22, 5, 23, 486646, tzinfo=utc), max_length=400)),
                ('message', models.TextField(blank=True, default='[]', max_length=100000000)),
                ('message_count', models.DecimalField(decimal_places=2, default=0, max_digits=50)),
                ('active', models.CharField(blank=True, default='True', max_length=400)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
