# Generated by Django 3.0.6 on 2022-06-21 22:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('remote', '0006_userdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='last_seen',
            field=models.CharField(blank=True, default=datetime.datetime(2022, 6, 21, 22, 5, 35, 767918, tzinfo=utc), max_length=400),
        ),
    ]
