# Generated by Django 3.0.6 on 2022-06-21 23:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('remote', '0007_auto_20220621_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='name',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='last_seen',
            field=models.CharField(blank=True, default=datetime.datetime(2022, 6, 21, 23, 21, 30, 254912, tzinfo=utc), max_length=400),
        ),
    ]
