# Generated by Django 3.0.6 on 2022-06-22 00:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('remote', '0008_auto_20220622_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='last_seen',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
